# This is the extensive config for VoidBox. It is recommended to use certain defaults unless you know what you are doing.
# If you are unsure about a certain option, please refer to the comments.
# If you are still unsure, do NOT RATE THIS PLUGIN POORLY! Join the Discord server and ask for help!
# https://discord.gg/zUMCxcFEYy (Discord invite link)